### ISSUE TITLE
/<cid>/path/to/file paths are not considered valid paths

### ISSUE THREAD

**Issue by kishansagathiya** [ipfs/go-path#19]
https://github.com/ipfs/go-path/blob/1bd072233a4bb2c9d6aabceea7cd16ea3cd23973/path.go#L22-L27

but when I try, I see
```
$ ipfs get /QmbkfHeLFHzKR9723HVgktuFb8dURv9jG2ez6SLq1gjQfG
Error: invalid 'ipfs ref' path
$ ipfs get /QmbkfHeLFHzKR9723HVgktuFb8dURv9jG2ez6SLq1gjQfG/temp2/im.gif
Error: invalid 'ipfs ref' path
```

Either description should be changed or we should start accepting those paths. I am in favour of adding support for that path pattern, but I wonder if accepting those paths would create problems for ipfs-based projects.

**Comment by magik6k** [comment]
The doc is wrong, CID-based paths are supported as `<cid>/path/to/file` (note lack of leading slash). 

> start accepting those paths

At least for now, until we figure out MFS paths in CoreAPI I wouldn't like to add more valid patterns here, just to leave more options open.
