### ISSUE TITLE
CIDs containing "/" cannot be parsed

### ISSUE THREAD

**Issue by hsanjuan** [ipfs/go-path#54]
Currently there is no way to express a path that contains a base64-formatted CID when it contains forward slashes.

Perhaps there should be a way of scaping "/" in the CID element of paths (which I think are either `<CID>/path` or `/ipfs/<CID>/path` or `/ipns/<CID>/path`).

**Comment by ribasushi** [comment]
@hsanjuan see also https://github.com/ipfs/go-ipfs/issues/7739

I personally just switched everything I do to b64urlenc ( `u` multibase ), but that's hardly a generic solution

**Comment by Jorropo** [comment]
> @hsanjuan see also [ipfs/go-ipfs#7739](https://github.com/ipfs/go-ipfs/issues/7739)
> 
> I personally just switched everything I do to b64urlenc ( `u` multibase ), but that's hardly a generic solution

This came from a discourse post, where I've said the exact same thing :D
https://discuss.ipfs.io/t/how-are-base64-encoded-cids-handled-when-they-have-in-them/13656/2?u=jorropo

I guess what we want is backslash escaping of `/` characters. So you could use base64, if you escape `/`.

**Comment by thattommyhall** [comment]
I should point out that I asked in the context of operating the PL gateway, where I am not in control of what people request

**Comment by markg85** [comment]
Would it not be sane to just remove the option to do base64 formatting. That format is just always going to cause troubles when used in a path context. A context that's likely in IPFS. On top of that, the proper alternative for it (b64urlenc) is there too.

I'd go as far as looking at all formatting options and kicking out all those that could break a path unintentionally.

**Comment by hacdias** [comment]
This repository is no longer maintained and has been copied over to [Boxo](https://github.com/ipfs/boxo). We are now in the process of reviewing issues and PRs and moving the ones that are still relevant. This issue has been merged with a few other issues, and moved to https://github.com/ipfs/boxo/issues/198.
