### ISSUE TITLE
merkledag.dagService does not implement fetcher.Factory (missing NewSession method)

### ISSUE THREAD

**Issue by gmelodie** [ipfs/go-path#56]
I'm using the following function to create a `GatewayHandler`:
```go
func NewGatewayHandler(bs blockstore.Blockstore) *GatewayHandler {
	dserv := merkledag.NewDAGService(blockservice.New(bs, nil))
	return &GatewayHandler{
		bs:       bs,
		dserv:    dserv,
		resolver: resolver.NewBasicResolver(dserv),
	}
}
```
It worked fine until I had to update `go-path` from version `0.0.7` to `0.2.1`. Here's the error I'm getting when compiling:
```bash
util/gateway/gateway.go:40:38: cannot use dserv (type *merkledag.dagService) as type fetcher.Factory in argument to resolver.NewBasicResolver:
	*merkledag.dagService does not implement fetcher.Factory (missing NewSession method)
```

Is there a workaround for this so I can use `dagService` here?

**Comment by ribasushi** [comment]
I have a hunch @willscott might know what to do here

**Comment by willscott** [comment]
after updating, path isn't directly given a dag service, but  rather uses `go-fetcher`
here's how it's done in IPFS: https://github.com/ipfs/go-ipfs/blob/09aed2d63b41b7dedf1ac0f9f5b293fcbc8cb6f8/fuse/readonly/readonly_unix.go#L72

that fetcher gets made at
https://github.com/ipfs/go-ipfs/blob/52c177ced94a1dca6f2a440ba9f25a184ff75ddb/core/node/core.go#L86-L104

using https://github.com/ipfs/go-fetcher

**Comment by ribasushi** [comment]
@gmelodie see https://github.com/application-research/estuary/pull/144 ( UNTESTED!!! )
